### ISSUE TITLE
Небольшой вопрос

### ISSUE THREAD

**Issue by drronn** [DieMetRik/mercury_esphome#2]
Здравствуйте! Занимался подключением счетчика меркурий 200.02 и все закончилось успешно, но на Вашей странице увидел скриншот с пробросом в Energy Management. Не подскажете как Вы это сделали? Сорри если оффтоп - просто на гитхабе нельзя отправлять сообщения в приват. Спасибо!

**Comment by DieMetRik** [comment]
Добрый день. Заходите на сервер умного дома. Далее /config/energy
Там добавляете сенсоры с kWh и фиксированную цену за kWh.

Скриншоты в папке /HomeAssistant

**Comment by DieMetRik** [comment]
Если все получится. Напишите, я закрою

**Comment by drronn** [comment]
Здравствуйте. Посмотрел, /config/energy - такой папки не было. Создал. Я правильно понимаю что в этой папке нужно создать yaml файл и записать туда что то вроде:
template:
  sensor:
    - name: "T1"
      unit_of_measurement: 'kWh'
      device_class: energy
      state_class: measurement
      state: '{{ states.sensor.tariff1.state }}'

?

**Comment by DieMetRik** [comment]
Не не. Откройте в браузере. http://[адрес home assistan]/config/energy

**Comment by DieMetRik** [comment]
Либо через:
Настройки->панели->Энергия
И прямо нажимайте на Энергия

**Comment by drronn** [comment]
Я вывел предварительно пункт энергия в боковую панель, но беда в том что там просто невозможно ничего добавить(на скриншоте) поэтому и подумал надо создавать папку и писать.
![765765765676767565](https://user-images.githubusercontent.com/85433913/169689175-568fbc25-6fba-4cde-a1a1-49e5e8e31d7a.JPG).

Если выбрать использовать фиксированную цену и написать 1 то он также не дает сохранять.

**Comment by DieMetRik** [comment]
Вверху нужно выбрать показаня со счетчика kWh

**Comment by DieMetRik** [comment]
Покажите мне ваши счетчик

**Comment by DieMetRik** [comment]
Покажите мне ваши счетчик

<img width="487" alt="Снимок экрана 2022-05-21 в 17 21 15" src="https://user-images.githubusercontent.com/31734768/169689598-db50da48-e3cb-4469-96fe-f517fe13c5b0.png">

**Comment by drronn** [comment]
А вот дело в том что в верхнем раскрывающемся меню ничего нет. То есть нельзя ничего выбрать.
![234786238746328764382764](https://user-images.githubusercontent.com/85433913/169689712-d2736c35-75ee-4592-a147-3143d714aaae.JPG)
А вообще пока вся конструкция пока выглядит вот так 
![IMG_20220520_123008](https://user-images.githubusercontent.com/85433913/169689794-4d96f13d-94be-45ab-b0ab-89098439c986.jpg)
если я Вас правильно понял.
В панели разработчика вот так
![dkhjfgshgf](https://user-images.githubusercontent.com/85433913/169689881-e02122b3-f636-4ded-b8e4-f52844d3b0fd.JPG)

**Comment by drronn** [comment]
После того как отправил понял - надо в атрибуты попробовать дописать чтобы стало как у Вас. Возможно это поможет.

**Comment by DieMetRik** [comment]
Да...Именно
Нужно обязательно добавить:
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing

**Comment by drronn** [comment]
Супер! Все получилось! Тему можно закрывать! Спасибо!
