### ISSUE TITLE
Как выяснить адрес счетчика?

### ISSUE THREAD

**Issue by Spirituss** [DieMetRik/mercury_esphome#5]
ПОдскажите, как узнать адрес счетчика, который нужно прописать в *.h? 
Это серийник или код из модбаса?

**Comment by DieMetRik** [comment]
Если никто не вмешивался в счетчик. То последние цифры серийника 

Slave id — все 8 цифр серийного номера, не включая год производства.

Это для 206

**Comment by Spirituss** [comment]
Серийник на самом счетчике написан?

**Comment by DieMetRik** [comment]
Да
